version: "3.8"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-pomo-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pomodoro_app_dev

volumes:
  postgres-pomo-data:
